name: breadcrumbs
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  http: ^1.2.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  firebase_auth: ^6.1.2
  google_sign_in: ^6.1.6
  firebase_messaging: ^16.0.4
  firebase_database: ^12.1.0
  flutter_colorpicker: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true